// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouVGvycDPtkPDU0jeYJyiFmTi-SunnGk',
    appId: '1:842635032158:web:3acbeba93ad64b495a66cf',
    messagingSenderId: '842635032158',
    projectId: 'schoolapplication-b1c37',
    authDomain: 'schoolapplication-b1c37.firebaseapp.com',
    storageBucket: 'schoolapplication-b1c37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbej1If8W2HKWSO0fLe9b_CoWEgJl62r0',
    appId: '1:842635032158:android:6da7b0ab99e9fc465a66cf',
    messagingSenderId: '842635032158',
    projectId: 'schoolapplication-b1c37',
    storageBucket: 'schoolapplication-b1c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xhz-0NcuLJwT9g2N5wdgoZEmdKlnSxc',
    appId: '1:842635032158:ios:1b6db1bd84dcd6af5a66cf',
    messagingSenderId: '842635032158',
    projectId: 'schoolapplication-b1c37',
    storageBucket: 'schoolapplication-b1c37.appspot.com',
    iosBundleId: 'com.example.universityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xhz-0NcuLJwT9g2N5wdgoZEmdKlnSxc',
    appId: '1:842635032158:ios:57188ffb225784755a66cf',
    messagingSenderId: '842635032158',
    projectId: 'schoolapplication-b1c37',
    storageBucket: 'schoolapplication-b1c37.appspot.com',
    iosBundleId: 'com.example.universityApp.RunnerTests',
  );
}
